# use single statement to avoid multiple precompile stages
using Pigeons,
    ADTypes,
    ArgMacros,
    Bijectors,
    BridgeStan,
    DelimitedFiles,
    Distributions,
    DynamicPPL,
    Enzyme,
    FillArrays,
    ForwardDiff,
    HypothesisTests,
    LinearAlgebra,
    LogDensityProblems,
    LogDensityProblemsAD,
    MCMCChains,
    MPI,
    MPIPreferences,
    OnlineStats,
    Pkg,
    Random,
    ReverseDiff,
    Serialization,
    SplittableRandoms,
    Statistics,
    JSON,
    SpecialFunctions,
    Test

is_windows_in_CI() = Sys.iswindows() && (get(ENV, "CI", "false") == "true")
