#!/bin/bash

description="List runs"


error=false
while getopts "h" opt; do
  case "$opt" in
    h)  error=true
      ;;
    *)  error=true
  esac
done

execs=results/all/

echo exec_name,qsub_id,git_commit,start,end,resources,command
for exec_name in `ls $execs`; 
do  
  exec_dir=$execs/$exec_name/
  exec_info_dir=$exec_dir/executionInfo/
  qsub_id=NA
  command=NA
  git_commit=NA
  start_hr=NA
  end_hr=NA
  [ -f $exec_info_dir/qsub_id.txt ] && qsub_id=$(cat $exec_info_dir/qsub_id.txt)
  [ -f $exec_info_dir/command.txt ] && command=$(cat $exec_info_dir/command.txt)
  [ -f $exec_info_dir/pbs-resources.txt ] && pbs_resources=$(cat $exec_info_dir/pbs-resources.txt)
  [ -f $exec_info_dir/git-commit.txt ] && git_commit=$(cat $exec_info_dir/git-commit.txt)
  [ -f $exec_info_dir/start-time.txt ] && start=$(cat $exec_info_dir/start-time.txt)
  [ -f $exec_info_dir/end-time.txt ] && end=$(cat $exec_info_dir/end-time.txt)
  [ -f $exec_info_dir/start-time.txt ] && start_hr=$(date -d @$start)
  [ -f $exec_info_dir/end-time.txt ] && end_hr=$(date -d @$end)

  echo $exec_name,$qsub_id,$git_commit,$start_hr,$end_hr,$pbs_resources,$command
done